[package]
name = "ipmark"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1"           # For IPv4/IPv6 regex matching
maxminddb = "0.22"    # For MaxMind GeoIP2 (City + ASN) lookups
lazy_static = "1"     # If you want to compile regex once globally
lru = "0.9"   # LRU cache for storing previous lookups
ipaddress = "0.1.3"
encoding_rs = "0.8"
byteorder = "1.5"
clap = { version = "4.6.1", features = ["derive", "env"] }
